<a href="https://colab.research.google.com/github/juanmager/EstructurasDeDatos/blob/master/TP_4_Arreglos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Declaración de vectores y matrices

In [ ]:
import numpy as np

vector = np.zeros(10,int)

print("Vector")
print(vector)

matriz = np.zeros((3,4),int)

print("\nMatriz")
print(matriz)

Vector
[0 0 0 0 0 0 0 0 0 0]

Matriz
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Acceso con índices / posiciones

In [ ]:
import numpy as np

################Unidimensionales##################
print("################Unidimensionales##################")

vector = np.zeros((10),int)

print("Vector de ceros")
print(vector)

vector[0] = 20
vector[5] = 10
#vector[10] = 50

print("Vector con modificaciones")
print(vector)
print(vector[2:6])

################Bidimensionales##################
print("\n################Bidimensionales##################")

matriz = np.zeros((3,4),int)

print("Matriz de ceros")
print(matriz)

matriz[0,0] = 20
matriz[0][2] = 10
matriz[1][3] = 50

print("Matriz con modificaciones")
print(matriz)
print("Primer Fila (matriz[0])")
print(matriz[0])
print("Segunda Fila (matriz[1])")
print(matriz[1])
print("Elemento fila 1 columna 3")
print(matriz[1,3])

print(matriz[1:,2:])

################Unidimensionales##################
Vector de ceros
[0 0 0 0 0 0 0 0 0 0]
Vector con modificaciones
[20  0  0  0  0 10  0  0  0  0]
[ 0  0  0 10]

################Bidimensionales##################
Matriz de ceros
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Matriz con modificaciones
[[20  0 10  0]
 [ 0  0  0 50]
 [ 0  0  0  0]]
Primer Fila (matriz[0])
[20  0 10  0]
Segunda Fila (matriz[1])
[ 0  0  0 50]
Elemento fila 1 columna 3
50
[[ 0 50]
 [ 0  0]]


### Medición de dimensiones

In [ ]:
import numpy as np

################Unidimensionales##################
print("################Unidimensionales##################")
vector = np.zeros((10),int)

print("Vector de ceros")
print(vector)
print("Longitud de vector (cantidad de elementos)")
print(len(vector))

################Bidimensionales##################
print("\n################Bidimensionales##################")
matriz = np.zeros((3,4),int)

print("Matriz de ceros")
print(matriz)

print("Cantidad de filas (len(matriz))")
print(len(matriz))
print("Cantidad de columnas (len(matriz[0]))")
print(len(matriz[0]))
print("Dimensión de matriz")
print(matriz.shape)
filas,columnas=matriz.shape

print(filas)
print(columnas)



################Unidimensionales##################
Vector de ceros
[0 0 0 0 0 0 0 0 0 0]
Longitud de vector (cantidad de elementos)
10

################Bidimensionales##################
Matriz de ceros
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Cantidad de filas (len(matriz))
3
Cantidad de columnas (len(matriz[0]))
4
Dimensión de matriz
(3, 4)
3
4


### Recorridos de vectores

In [ ]:
import numpy as np

vector = np.array([3,5,1,8,14])

print(vector)
print("Recorrido sobre elementos directamente (sentido directo)")
for elemento in vector:
  print(elemento)

print("\n",vector)
print("Recorrido sobre elementos directamente (sentido inverso)")
for elemento in reversed(vector):
  print(elemento)

print("\n",vector)
print("Recorrido usando indices / posiciones (sentido directo)")
for posicion in range(len(vector)):
  print("Posición:",posicion)
  print(vector[posicion])

print("\n",vector)
print("Recorrido usando indices / posiciones (sentido inverso)")
for posicion in reversed(range(len(vector))):
  print("Posición:",posicion)
  print(vector[posicion])





 [ 3  5  1  8 14]
Recorrido usando indices / posiciones (sentido inverso)
Posición: 4
14
Posición: 3
8
Posición: 2
1
Posición: 1
5
Posición: 0
3


### Recorridos de matrices

In [ ]:
import numpy as np

matriz = np.array([[3,5,1],[2,8,14],[12,3,9],[23,4,0]])

print(matriz)
print("\nRecorrido sobre elementos directamente (sentido directo)")
for fila in matriz:
  for elemento in fila:
    print(elemento)

print("\n",matriz)
print("Recorrido sobre elementos directamente (sentido inverso)")
for fila in reversed(matriz):
  for elemento in reversed(fila):
    print(elemento)

print("\n",matriz)
print("Recorrido usando indices / posiciones (sentido directo)")
nFilas,nColumnas = matriz.shape
for posicionFila in range(nFilas):
  for posicionColumna in range(nColumnas):
    print("Posición:",posicionFila,",",posicionColumna)
    print(matriz[posicionFila , posicionColumna])

print("\n",matriz)
print("Recorrido usando indices / posiciones (sentido inverso)")
for posicionFila in reversed(range(len(matriz))):
  for posicionColumna in reversed(range(len(matriz[posicionFila]))):
    print("Posición:",posicionFila,",",posicionColumna)
    print(matriz[posicionFila][posicionColumna])





 [[20  0 10  0]
 [ 0  0  0 50]
 [ 0  0  0  0]]
Recorrido usando indices / posiciones (sentido inverso)
Posición: 2 , 3
0
Posición: 2 , 2
0
Posición: 2 , 1
0
Posición: 2 , 0
0
Posición: 1 , 3
50
Posición: 1 , 2
0
Posición: 1 , 1
0
Posición: 1 , 0
0
Posición: 0 , 3
0
Posición: 0 , 2
10
Posición: 0 , 1
0
Posición: 0 , 0
20


### Arreglos de caracteres y tipo *str*

In [ ]:
import numpy as np

################Arreglos de caracteres##################
print("################Arreglos de caracteres##################")

cadena = np.array(['h','o','l','a'])

print(cadena)
cadena[1] = 'f'
print(cadena)

################Tipo str##################
print("\n################Tipo str##################")

cadenaStr = "hola"

print(cadenaStr)
print(cadenaStr[0])

cadenaStr[1] = 'f'

<class 'tuple'>


### Cosas a tener en cuenta

In [ ]:
import numpy as np

vector1 = np.array([2,3,6,1])
vector2 = vector1

print("vector1 =",vector1)
print("vector2 =",vector2)

print("\nModificamos solo a vector1")

vector1[1] = 200

print("vector1 =",vector1)
print("vector2 =",vector2)


vector1 = [2 3 6 1]
vector2 = [2 3 6 1]

Modificamos solo a vector1
vector1 = [  2 200   6   1]
vector2 = [  2 200   6   1]


### Arreglos como parámetros de funciones / procedimientos

In [ ]:
import numpy as np

def funcionEjemplo(vector):
  vector[1] = 20

v = np.array([2,5,3,9])

print("v =",v)

funcionEjemplo(v)

print("\nLuego de ejecutar funcionEjemplo")
print("v =",v)

v = [2 5 3 9]

Luego de ejecutar funcionEjemplo
v = [ 2 20  3  9]
